language: cpp

env:
  global:
    - GLOG_v=1
    - GLOG_logtostderr=1

cache:
  directories:
    - .deps

before_install:
  - cd /tmp
  - wget https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-Linux-x86_64.sh -O cmake-install.sh
  - chmod u+x cmake-install.sh
  - sudo ./cmake-install.sh --skip-license --prefix=/usr
  - rm cmake-install.sh

install:
  - cd $TRAVIS_BUILD_DIR
  - sudo ./install-deps.sh

script:
  - mkdir -p build
  - cd build
  - cmake .. -DBUILD_CLIENT=OFF -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Debug
  - make -j$(nproc)
  - ctest --output-on-failure
