def gen_netem_script(netems, filters):
    '''Generates a tc netem script

    netems  a list of arguments for netem qdiscs
    filters a list with the same size as 'netems'. Each element is a list of
            IP addresses that will be filtered and queued to the corresponding qdisc
    '''
    assert len(netems) == len(filters), "Number of filter groups must match number of netem argument groups"

    script = [
        "# Generated by netem.py",
        "set +e",
        "tc qdisc del dev eth0 root 2> /dev/null",
        "set -ex",
        "tc qdisc add dev eth0 root handle 1: htb"
    ]

    for i, netem in enumerate(netems):
        script += [
            f"tc class add dev eth0 parent 1: classid 1:{i+1} htb rate 1gbit",
            f"tc qdisc add dev eth0 parent 1:{i+1} handle {(i+1)*10}: netem {netem}",
        ]
    for i, filter in enumerate(filters):
        for ip in filter:
            script += [
               f"tc filter add dev eth0 parent 1: protocol ip prio 1 u32 match ip dst {ip} flowid 1:{i+1}"
            ]
    script += [
        'set +x',
        'echo',
        'echo "***** QDISC ******"',
        'tc -col qdisc show dev eth0',
        'echo',
        'echo "***** CLASS ******"',
        'tc -col class show dev eth0',
        'echo',
        'echo "***** FILTER ******"',
        'tc -col filter show dev eth0',
        'echo',
    ]
    return '\n'.join(script)

