# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/modules.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/modules.proto',
  package='slog',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/modules.proto\x12\x04slog*\x9c\x01\n\x08ModuleId\x12\n\n\x06\x42ROKER\x10\x00\x12\n\n\x06SERVER\x10\x01\x12\r\n\tMHORDERER\x10\x02\x12\x0e\n\nLOCALPAXOS\x10\x03\x12\x0f\n\x0bGLOBALPAXOS\x10\x04\x12\r\n\tFORWARDER\x10\x05\x12\r\n\tSEQUENCER\x10\x06\x12\x0f\n\x0bINTERLEAVER\x10\x07\x12\r\n\tSCHEDULER\x10\x08\x12\n\n\x06WORKER\x10\tb\x06proto3'
)

_MODULEID = _descriptor.EnumDescriptor(
  name='ModuleId',
  full_name='slog.ModuleId',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BROKER', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MHORDERER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LOCALPAXOS', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GLOBALPAXOS', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FORWARDER', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SEQUENCER', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTERLEAVER', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SCHEDULER', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WORKER', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=30,
  serialized_end=186,
)
_sym_db.RegisterEnumDescriptor(_MODULEID)

ModuleId = enum_type_wrapper.EnumTypeWrapper(_MODULEID)
BROKER = 0
SERVER = 1
MHORDERER = 2
LOCALPAXOS = 3
GLOBALPAXOS = 4
FORWARDER = 5
SEQUENCER = 6
INTERLEAVER = 7
SCHEDULER = 8
WORKER = 9


DESCRIPTOR.enum_types_by_name['ModuleId'] = _MODULEID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
